name: build

on:
  push:
    branches:
      - main
    paths:
      - docker/**
      - .github/workflows/build.yml
  pull_request:
    branches:
      - main
    paths:
      - docker/**
      - .github/workflows/build.yml

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NAMESPACE: ${{ vars.NAMESPACE || 'kubernetesloong64' }}
    strategy:
      fail-fast: false
      matrix:
        base:
          - os: anolis
            dockerfile: Dockerfile.anolis
          - os: debian
            dockerfile: Dockerfile.debian
          - os: debian-slim
            dockerfile: Dockerfile.debian
          - os: openeuler
            dockerfile: Dockerfile.openeuler
        jdk:
          - version: "8"
          - version: "11"
          - version: "17"
          - version: "21"
          - version: "25"
          - version: "26"
        maven:
          - version: "3.9.16"

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Login to Docker
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        if: github.event_name == 'push'
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: |
          PREFIX="${{ env.NAMESPACE }}/maven-loong64"
          TAG="${PREFIX}:${{ matrix.maven.version }}-${{ matrix.jdk.version }}-${{ matrix.base.os }}"
          is_push=${{ github.event_name == 'push' && '--push' || '--load' }}
          echo "==> Building ${TAG}"
          docker buildx build \
            --no-cache \
            -f "docker/${{ matrix.base.dockerfile }}" \
            $is_push \
            --build-arg "JDK_VERSION=${{ matrix.jdk.version }}" \
            --build-arg "MAVEN_VERSION=${{ matrix.maven.version }}" \
            --build-arg "OS=${{ matrix.base.os }}" \
            --platform linux/loong64 \
            -t "${TAG}" \
            docker/
          echo "==> Done: ${TAG}"
